export const ApplicationFormInitialValues = {
    job_title: "",
    company_name: "",
    employment_type_id: "",
    applicant_names: "",
    applicant_last_names: "",
    applicant_email: "",
    applicant_phone: "",
    applicant_linkedin: "",
    applicant_portfolio_link: "",
    applicant_country: "",
    applicant_city: "",
    applicant_address: "",
    cv: null,
    monthly_expected_salary: "",
    availability_id: "",
    work_modality_id: "",
    educations: [],
    experiences: [],
  }