import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Navbar } from "@/components/ui";
import HailIcon from "@mui/icons-material/Hail";
import { Box } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <Navbar
            icon={HailIcon}
            title="Postulaciones App"
            buttonText="Visitar formulario"
            buttonLink=""
          />
          <Box
            sx={{
              maxWidth: "1400px", // Equivalente a max-w-7xl
              mx: "auto", // Equivalente a mx-auto
              px: {
                xs: 2, // Padrastro predeterminado para pantallas extra pequeñas
                sm: 3, // Equivalente a sm:px-6 (24px = 3 * 8px)
                lg: 4, // Equivalente a lg:px-8 (32px = 4 * 8px)
              },
              my: 3,
            }}
          >
            {/* Tu contenido aquí */}
            {children}
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
